version: "2"

run:
  tests: true
  build-tags:
    - all

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - importas
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    gocritic:
      disabled-checks:
        - commentFormatting

    errcheck:
      check-blank: false
      exclude-functions:
        - 'fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy'

    dupl:
      # tokens count to trigger issue, 150 by default
      threshold: 500

    misspell:
      ignore-rules:
        - hdinsight

    revive:
      enable-all-rules: true
      rules:
        - name: cyclomatic
          disabled: true
        - name: argument-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: file-header
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: banned-characters
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: add-constant
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: var-naming
          disabled: true
        - name: deep-exit
          disabled: true
        - name: exported
          disabled: false
          arguments:
            - 'disableStutteringCheck'
        - name: unused-parameter
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: nested-structs
          disabled: true

  exclusions:
    paths:
      - bin
      - docs
      - client/mocks
      - resources/forks
      - codegen

    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - dupl
          - gocritic
        # Exclude some linters from running on resource files.
      - path: resources(\\|\/).*\.go
        linters:
          - dupl
      # Exclude some linters from running on services files.
      - path: services\.go
        linters:
          - dupl

formatters:
  enable:
    - gofmt

  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

  exclusions:
    paths:
      - bin
      - docs
      - client/mocks
      - resources/forks
      - codegen
